"use client";
import "./globals.css";
import "./globals.scss";
import { Inter } from "next/font/google";
import { AuthContextProvider } from "@/context/AuthContext";
import { ChatContextProvider } from "@/context/ChatContext";

import { useContext } from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  // data.isLoading ? <Spinner /> : children
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthContextProvider>
          <ChatContextProvider>{children}</ChatContextProvider>
        </AuthContextProvider>
      </body>
    </html>
  );
}
