"use client";
import "./globals.css";
import "./globals.scss";
import { Inter } from "next/font/google";
import { AuthContextProvider } from "@/context/AuthContext";
import { ChatContextProvider } from "@/context/ChatContext";

import { useContext } from "react";
import Spinner from "@/components/Spinner";
import { SpinnerContextProvider } from "@/context/SpinnerContext";
import { SpinnerContext } from "@/context/SpinnerContext";
import { SocketProvider } from "@/context/SocketContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const checkLoading = () => {
    const { data } = useContext(SpinnerContext);
  };
  // data.isLoading ? <Spinner /> : children
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthContextProvider>
          <ChatContextProvider>
            <SpinnerContextProvider>
              <SocketProvider>{children}</SocketProvider>
            </SpinnerContextProvider>
          </ChatContextProvider>
        </AuthContextProvider>
      </body>
    </html>
  );
}
